### ISSUE TITLE
Anchor links for headers

### ISSUE THREAD

**Issue by ethnt** [siteleaf/siteleaf.com#9]
Having anchor links for headers would be helpful, especially so we could link straight to the Plans FAQ.

**Comment by sskylar** [comment]
This would be great on learn.siteleaf.com too...

``` yaml
markdown: kramdown
kramdown:
  auto_ids: true # Auto-generate ID's for headings
```
